name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      USERNAME_TO_CHECK: ${{ secrets.USERNAME_TO_CHECK }}
      PASSWORD_TO_CHECK: ${{ secrets.PASSWORD_TO_CHECK }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Checkout server
        uses: actions/checkout@v4
        with:
          repository: cypress-io/cypress-realworld-app
          path: cypress-realworld-app
      - name: Install Server
        run: cd cypress-realworld-app && yarn install
      - name: Checkout test
        uses: actions/checkout@v4
        with:
          path: tests

      - name: Install Test
        run: cd tests && npm install

      - name: Run Tests
        run: |
          cd cypress-realworld-app && yarn dev &
          cd tests && sleep 120 && npm run wdio:chrome
          continue-on-error: true

      - name: Generate Allure report
        run: npm run allure:report

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./reports/allure-report
      
          
     